name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Nix
        uses: cachix/install-nix-action@v24
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
            accept-flake-config = true
      
      - name: Check Nix flake
        run: nix flake check --no-build
      
      - name: Check formatting
        run: nix fmt -- --check
      
      - name: Show flake info
        run: |
          nix flake show
          nix flake metadata
      
      - name: Validate flake outputs
        run: |
          nix eval .#darwinConfigurations.hank-mbp-m4.config.system.build.toplevel
      
      - name: Install just
        uses: extractions/setup-just@v1
      
      - name: Check justfile
        run: |
          just --version
          just --evaluate
          just --fmt --check

  test:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Nix
        uses: cachix/install-nix-action@v24
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
      
      - name: Dry build
        run: nix build .#darwinConfigurations.hank-mbp-m4.system --dry-run
      
      - name: Test nix develop
        run: nix develop --command echo "Development shell OK"

  build-darwin:
    runs-on: macos-latest
    needs: check
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            experimental-features = nix-command flakes
      
      - name: Setup Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      
      - name: Build Darwin configuration
        run: |
          nix build .#darwinConfigurations.hank-mbp-m4.system --no-link --print-out-paths
      
      - name: Run tests
        run: |
          chmod +x tests/test.sh
          ./tests/test.sh