name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: cachix/install-nix-action@v24
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      
      - name: Format Check
        run: nix fmt -- --check

  darwin-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: cachix/install-nix-action@v24
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      
      - name: Flake Check
        run: nix flake check
      
      - name: Structure Validation
        run: ./tests/lib/validate-structure.sh
      
      - name: Unit Tests
        run: ./tests/unit/test-modules.sh
      
      - name: Integration Tests
        run: ./tests/integration/test-full-build.sh
      
      - name: Build Darwin Configuration (dry-run)
        run: nix build .#darwinConfigurations.hank-mbp-m4.system --dry-run

  linux-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: cachix/install-nix-action@v24
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      
      - name: Test NixOS Module
        run:  < /dev/null | 
          nix-instantiate --eval --expr "
          let
            pkgs = import <nixpkgs> {};
            lib = pkgs.lib;
          in
            import ./modules/nixos/default.nix { inherit lib pkgs config; config = {}; }
          " > /dev/null
      
      - name: Test Import Library
        run: |
          nix-instantiate --eval --expr "
            import ./lib/imports.nix { lib = (import <nixpkgs> {}).lib; }
          " > /dev/null
